const ImageStyleLists = [
    { name: "미니멀리즘", description: "간결하고 단순한 디자인." },
    { name: "복고풍", description: "과거의 패션, 예술 스타일을 현대적으로 재해석한 스타일." },
    { name: "펑크", description: "반항적이고 대담한 스타일." },
    { name: "보헤미안", description: "자유분방하고 예술적인 스타일." },
    { name: "고전주의", description: "고대 그리스, 로마 예술에서 영감을 받은 스타일." },
    { name: "아방가르드", description: "실험적이고 혁신적인 스타일." },
    { name: "스트리트웨어", description: "힙합 문화에서 영향을 받은 캐주얼한 스타일." },
    { name: "빈티지", description: "특정 시대의 오래된 패션 스타일." },
    { name: "로맨틱", description: "여성스럽고 로맨틱한 스타일." },
    { name: "그런지", description: "거칠고 낡은 느낌의 스타일." },
    { name: "스포티", description: "운동복에서 영감을 받은 활동적인 스타일." },
    { name: "빅토리아", description: "19세기 영국 빅토리아 시대의 스타일." },
    { name: "아르누보", description: "자연의 곡선과 식물 모티프가 특징인 예술 스타일." },
    { name: "아르데코", description: "기하학적 형태와 대담한 색상이 특징인 1920년대 스타일." },
    { name: "모더니즘" , description: "현대적이고 기능적인 디자인 스타일." },
    { name: "코티지코어", description: "전원적이고 아늑한 느낌의 스타일." },
    { name: "키치", description: "일부러 촌스럽고 과장된 스타일." },
    { name: "인더스트리얼", description: "거친 산업적 요소를 포함한 스타일." },
    { name: "사이버펑크", description: "고도로 기술적이고 미래적인 스타일." },
    { name: "에스닉", description: "다양한 문화에서 영감을 받은 스타일." },
    { name: "모노크롬", description: "단색을 사용하는 스타일." },
    { name: "서스테이너블", description: "환경을 생각하는 지속 가능한 스타일." },
    { name: "카운트리", description: "시골적이고 전통적인 스타일." },
    { name: "피트니스", description: "운동과 건강에 초점을 맞춘 스타일." },
    { name: "팝아트", description: "대중문화에서 영감을 받은 밝고 대담한 스타일." },
    { name: "젠더뉴트럴", description: "성별 구분 없는 스타일." },
    { name: "하이테크", description: "최신 기술을 강조하는 스타일." },
    { name: "노마드", description: "자유롭고 유동적인 생활 방식을 반영한 스타일." },
];
export default ImageStyleLists;
