const ImageStyleLists = [
    { name: "미니멀"},
    { name: "뮤지컬"},
    { name: "전쟁"},
    { name: "미스테리"},
    { name: "역사"},
    { name: "실험"},
    { name: "도시"},
    { name: "고전"},
    { name: "로맨스"},
    { name: "아포칼립스"},
    { name: "액션"},
    { name: "19세기 영국"},
    { name: "판타지"},
    { name: "누아르"},
    { name: "모던" },
    { name: "가족"},
    { name: "코미디"},
    { name: "스릴러"},
    { name: "사이버펑크"},
    { name: "슈퍼 히어로"},
    { name: "흑백"},
    { name: "다큐멘터리"},
    { name: "서부"},
    { name: "스포츠"},
    { name: "애니메이션"},
    { name: "드라마"},
    { name: "SF"},
    { name: "모험"},
];
export default ImageStyleLists;
